keys:
  users:
    - &tom_age age1yvge60ljjjlyx8lvkcle98zhja7xjdkfg40m4nzqu2kr97epx9es23fnzu
    - &tom_pgp 1663EC2E7C8C8E95BE959EB3ABF77DD0DF58CFF4
  hosts:
    - &thor age1gq2wj3dpjnjd7z4ev7ugenwnvlqlyfn2pauzt2jp6g788x060dsqrysqrs

creation_rules:
  - path_regex: home/tom/hosts/.*/secrets\.ya?ml$
    key_groups:
      - age:
        - *tom_age
        pgp:
        - *tom_pgp
  - path_regex: hosts/thor/secrets\.ya?ml$
    key_groups:
      - age:
        - *thor
        pgp:
        - *tom_pgp
  - path_regex: hosts/secrets\.ya?ml$
    key_groups:
      - age:
        - *thor
        pgp:
        - *tom_pgp
