keys:
  users:
    - &tom_age age1ksqwe7yqefqs6pupzef9guznxq8srwjul8t8rl5mj0f9c83lhs2sc6ljmx
    - &tom_pgp 1663EC2E7C8C8E95BE959EB3ABF77DD0DF58CFF4
  hosts:
    - &thor age1wztfp8w2upv6y5dcas8kfqqv7mcggr907y5tvdqzqu86etp4adxqpucpk7

creation_rules:
  - path_regex: home/tom/hosts/.*/secrets\.ya?ml$
    key_groups:
      - age:
        - *tom_age
        pgp:
        - *tom_pgp
  - path_regex: hosts/thor/secrets\.ya?ml$
    key_groups:
      - age:
        - *thor
        pgp:
        - *tom_pgp
  - path_regex: hosts/secrets\.ya?ml$
    key_groups:
      - age:
        - *thor
        pgp:
        - *tom_pgp
