keys:
  - &thesse_gpg 1663EC2E7C8C8E95BE959EB3ABF77DD0DF58CFF4
  - &tyr age16qpsxrlwttw7l3nhs3vdcvasun3xj2w43xhn9jxx0nmn2cfg6yds285rwn

creation_rules:
  - path_regex: modules/sops/secrets\.yaml$
    key_groups:
      - pgp:
          - *thesse_gpg
        age:
          - *tyr

  - path_regex: modules/hosts/tyr/secrets\.yaml$
    key_groups:
      - pgp:
          - *thesse_gpg
        age:
          - *tyr
